// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_nutricao.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8Esde8OkYLvjFfHCi8f5Et6se0GX_oE',
    appId: '1:515368188667:web:69317de12fb2176e300e5e',
    messagingSenderId: '515368188667',
    projectId: 'database-alimentos-c68e2',
    authDomain: 'database-alimentos-c68e2.firebaseapp.com',
    storageBucket: 'database-alimentos-c68e2.firebasestorage.app',
    measurementId: 'G-W67FDGEMMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqcSQNgFVqW_l-nuohfHQ4-wiuQOqP_6Y',
    appId: '1:515368188667:android:65ea03c9aa8b5b36300e5e',
    messagingSenderId: '515368188667',
    projectId: 'database-alimentos-c68e2',
    storageBucket: 'database-alimentos-c68e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrzXqh5Os2sOJzmIUWX9AcRBiu2Nx-5o',
    appId: '1:515368188667:ios:9156c9129a38fb3a300e5e',
    messagingSenderId: '515368188667',
    projectId: 'database-alimentos-c68e2',
    storageBucket: 'database-alimentos-c68e2.firebasestorage.app',
    iosBundleId: 'com.seudominio.nutricao',
  );
}
